### ISSUE TITLE
Broken link for repository

### ISSUE THREAD

**Issue by breun** [apache/maven-apache-parent#242]
The link for this GitHub repository on https://github.com/apache/maven-apache-parent is https://maven.apache.org/pom/asf/ but that link returns 404 Not Found.

The header of the README (https://github.com/apache/maven-apache-parent/blob/master/README.md) also contains this broken link.

When I visit https://maven.apache.org and click Parent POMs (https://maven.apache.org/pom/index.html), I also get 404 Not Found.

**Comment by slawekjaranowski** [comment]
Thanks ... there is a ASF infrastructure issue 
Many ASF site have a 404 ... eg https://commons.apache.org/

**Comment by slawekjaranowski** [comment]
https://status.apache.org/

**Comment by breun** [comment]
Thanks, works again indeed!
