### ISSUE TITLE
maven-javadoc-plugin fails to generate java docs for java version 1.8 when using apache parent pom version 33

### ISSUE THREAD

**Issue by vinishjail97** [apache/maven-apache-parent#249]
Hey Apache Maven Team. 

We are seeing an issue in generating java docs when using the latest version (33) for apache parent pom. 
`mvn deploy -Prelease -DskipTests -DdeployArtifacts=true ` fails the following error. 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.8.0:jar (attach-javadocs) on project xtable-api: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1
[ERROR] /Users/vinishreddy/helm/configs/incubator-xtable/xtable-api/target/delombok/org/apache/xtable/spi/extractor/ExtractFromSource.java:38: error: method references are not supported in -source 7
[ERROR]     Iterator<TableChange> tableChangeIterator = commitsBacklog.getCommitsToProcess().stream().map(conversionSource::getTableChangeForCommit).iterator();
[ERROR]                                                                                                                     ^
[ERROR]   (use -source 8 or higher to enable method references)
[ERROR] /Users/vinishreddy/helm/configs/incubator-xtable/xtable-api/target/delombok/org/apache/xtable/spi/sync/TableFormatSync.java:64: error: lambda expressions are not supported in -source 7
[ERROR]         results.put(conversionTarget.getTableFormat(), getSyncResult(conversionTarget, SyncMode.FULL, internalTable, target -> target.syncFilesForSnapshot(snapshot.getPartitionedDataFiles()), startTime, snapshot.getPendingCommits()));
```

But after downgrading to version 31 there's no issue in generating docs, you can find the parent pom xml for the project here.
https://github.com/apache/incubator-xtable/blob/main/pom.xml 

Do you think this is regression in 33 version or some new property needs to be set ?

**Comment by kwin** [comment]
You should not overwrite m-javadoc-p and m-compiler-p configuration with regards to target bytecode in https://github.com/apache/incubator-xtable/blob/15cc0f8b536b7b5ead16561c49df4ffcd0b36ee4/pom.xml#L891 and https://github.com/apache/incubator-xtable/blob/15cc0f8b536b7b5ead16561c49df4ffcd0b36ee4/pom.xml#L609. This is all done in ASF parent according to the property value `maven.compiler.target`
